# -*- coding: utf-8 -*-
"""ANPR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gsRLS7Hii9Pthw4wj5DmADzFt1ciY5Os
"""



!unzip "/content/ANPR.v2i.yolov8.zip" -d "/content/dataset"

!pip install ultralytics

from ultralytics import YOLO

!cat /content/dataset/data.yaml

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/dataset/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16
)

from IPython.display import Image, display

print("RESULTS")
display(Image('/content/runs/detect/train/results.png'))

print("CONFUSION MATRIX")
display(Image('/content/runs/detect/train/confusion_matrix.png'))

print("PRECISION-RECALL CURVE")
display(Image('/content/runs/detect/train/BoxPR_curve.png'))

print("F1 CURVE")
display(Image('/content/runs/detect/train/BoxF1_curve.png'))

print("PRECISION CURVE")
display(Image('/content/runs/detect/train/BoxP_curve.png'))

print("RECALL CURVE")
display(Image('/content/runs/detect/train/BoxR_curve.png'))

!pip install easyocr -q

import cv2
import easyocr
import matplotlib.pyplot as plt
from ultralytics import YOLO
from google.colab import files

MODEL_PATH = "/content/runs/detect/train/weights/best.pt"

model = YOLO(MODEL_PATH)

print("Model berhasil dimuat")

uploaded = files.upload()

image_path = list(uploaded.keys())[0]

results = model(
    image_path,
    save=True,
    conf=0.25
)

print("Deteksi selesai")

import os
from IPython.display import Image, display

predict_folder = "/content/runs/detect/predict"

files_pred = os.listdir(predict_folder)

print(files_pred)

display(Image(
    f"/content/runs/detect/predict/{files_pred[0]}"
))

reader = easyocr.Reader(['en'])

import cv2
import easyocr
import matplotlib.pyplot as plt
from ultralytics import YOLO

# ==========================================
# LOAD MODEL
# ==========================================

model = YOLO("/content/runs/detect/train/weights/best.pt")

# ==========================================
# LOAD OCR
# ==========================================

reader = easyocr.Reader(['en'])

# ==========================================
# PILIH GAMBAR
# ==========================================

image_path = list(uploaded.keys())[0]

img = cv2.imread(image_path)

# ==========================================
# DETEKSI PLAT
# ==========================================

results = model(img)

# ==========================================
# PROSES SETIAP PLAT YANG TERDETEKSI
# ==========================================

for r in results:

    boxes = r.boxes.xyxy.cpu().numpy()
    confs = r.boxes.conf.cpu().numpy()

    for box, conf in zip(boxes, confs):

        x1, y1, x2, y2 = map(int, box)

        # Crop area plat
        crop = img[y1:y2, x1:x2]

        # ==================================
        # TAMPILKAN HASIL CROP
        # ==================================

        plt.figure(figsize=(10,4))
        plt.imshow(cv2.cvtColor(crop, cv2.COLOR_BGR2RGB))
        plt.title("Plat Terdeteksi")
        plt.axis("off")
        plt.show()

        # ==================================
        # PREPROCESSING OCR
        # ==================================

        gray = cv2.cvtColor(
            crop,
            cv2.COLOR_BGR2GRAY
        )

        gray = cv2.resize(
            gray,
            None,
            fx=3,
            fy=3,
            interpolation=cv2.INTER_CUBIC
        )

        gray = cv2.GaussianBlur(
            gray,
            (3,3),
            0
        )

        _, thresh = cv2.threshold(
            gray,
            0,
            255,
            cv2.THRESH_BINARY + cv2.THRESH_OTSU
        )

        # ==================================
        # TAMPILKAN HASIL PREPROCESSING
        # ==================================

        plt.figure(figsize=(10,4))
        plt.imshow(thresh, cmap='gray')
        plt.title("Hasil Preprocessing OCR")
        plt.axis("off")
        plt.show()

        # ==================================
        # OCR
        # ==================================

        ocr_result = reader.readtext(
        gray,
        allowlist='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
        detail=0
        )

        nomor_plat = " ".join(ocr_result)

        # ==================================
        # OUTPUT
        # ==================================

        print("="*50)
        print("HASIL DETEKSI PLAT")
        print("="*50)

        print(
            "Confidence :",
            round(float(conf)*100,2),
            "%"
        )

        print(
            "Nomor Plat :",
            nomor_plat
        )

        print("="*50)